### ISSUE TITLE
Thanks for you awesome package

### ISSUE THREAD

**Issue by godu** [rclark/kinesis-readable#10]
I forked your project to adapt it to dynamodb-streams.

Check it out [HERE](https://github.com/coorpacademy/serverless-plugins/tree/master/packages/dynamodb-streams-readable).

If your want to merge with your project or something else, it will be a pleasure for me to help you.

**Comment by rclark** [comment]
Very cool! It has been a long time since I worked on this project, but I recall when I made this originally that dynamodb stream use-cases kept coming up. 

If you would be interested in bringing that dynamodb functionality into this repository, I'd be more than willing to work with you on figuring out how we could do that. We could make a new major version and give it a new name that isn't coupled to kinesis...
